const styles = {
	page: {
		background: 'var(--color-main-background)',
		minHeight: 'calc(100vh - var(--header-height))',
		width: '100%',
		maxWidth: 'none',
		padding: '20px',
		boxSizing: 'border-box',
		overflow: 'auto',
	},
	layout: {
		display: 'grid',
		gridTemplateColumns: '220px minmax(0, 1fr)',
		gap: '16px',
		alignItems: 'start',
		width: '100%',
		minWidth: 0,
	},
	menu: {
		display: 'flex',
		flexDirection: 'column',
		gap: '8px',
	},
	menuItem: {
		textAlign: 'left',
		padding: '10px 12px',
		borderRadius: '8px',
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		cursor: 'pointer',
		fontSize: '14px',
	},
	menuItemActive: {
		background: 'var(--color-primary-element)',
		color: 'var(--color-primary-element-text)',
		borderColor: 'var(--color-primary-element)',
	},
	content: {
		background: 'var(--color-main-background-translucent)',
		border: '1px solid var(--color-border)',
		borderRadius: '10px',
		padding: '16px',
		minHeight: '220px',
		width: '100%',
		minWidth: 0,
		overflow: 'auto',
	},
	formSection: {
		width: '100%',
	},
	form: {
		display: 'grid',
		gap: '10px',
	},
	fieldLabel: {
		fontWeight: 600,
		fontSize: '14px',
		color: 'var(--color-main-text)',
	},
	input: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '10px 12px',
		fontSize: '14px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		width: '100%',
		minWidth: 'min(100%, 320px)',
		maxWidth: '560px',
		boxSizing: 'border-box',
	},
	validationMessage: {
		margin: 0,
		color: 'var(--color-error)',
		fontSize: '13px',
	},
	hintText: {
		margin: 0,
		color: 'var(--color-text-maxcontrast)',
		fontSize: '13px',
	},
	submitButton: {
		marginTop: '6px',
		padding: '10px 12px',
		borderRadius: '8px',
		border: '1px solid var(--color-primary-element)',
		background: 'var(--color-primary-element)',
		color: 'var(--color-primary-element-text)',
		cursor: 'pointer',
		width: 'fit-content',
	},
	buttonRow: {
		display: 'flex',
		alignItems: 'center',
		gap: '10px',
	},
	clearButton: {
		marginTop: '6px',
		padding: '10px 12px',
		borderRadius: '8px',
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		cursor: 'pointer',
		width: 'fit-content',
	},
	pronounsRow: {
		display: 'grid',
		gridTemplateColumns: '1fr auto auto auto',
		gap: '8px',
		alignItems: 'center',
	},
	entryDeleteButton: {
		border: '1px solid transparent',
		background: 'transparent',
		color: 'var(--color-main-text)',
		padding: '2px 4px',
		fontSize: '12px',
		lineHeight: 1,
		cursor: 'pointer',
		borderRadius: '4px',
	},
	entryEditButton: {
		border: '1px solid transparent',
		background: 'transparent',
		color: 'var(--color-main-text)',
		padding: '2px 4px',
		fontSize: '12px',
		lineHeight: 1,
		cursor: 'pointer',
		borderRadius: '4px',
	},
	quickFillButton: {
		whiteSpace: 'nowrap',
		padding: '8px 10px',
		borderRadius: '8px',
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		cursor: 'pointer',
	},
	successMessage: {
		margin: 0,
		color: 'var(--color-success)',
		fontSize: '13px',
	},
	outputBox: {
		marginTop: '8px',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '10px 12px',
		fontSize: '13px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		minHeight: '96px',
		minWidth: 'min(100%, 320px)',
		width: '100%',
		maxWidth: '560px',
		boxSizing: 'border-box',
		resize: 'vertical',
	},
	templateBox: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '10px 12px',
		fontSize: '13px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		minHeight: '220px',
		minWidth: 'min(100%, 320px)',
		width: '100%',
		boxSizing: 'border-box',
		resize: 'vertical',
	},
	tableWrapper: {
		overflowX: 'auto',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
	},
	table: {
		width: '100%',
		borderCollapse: 'collapse',
	},
	tableHeader: {
		textAlign: 'left',
		padding: '10px 12px',
		fontSize: '13px',
		borderBottom: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
	},
	tableCell: {
		padding: '10px 12px',
		fontSize: '13px',
		borderBottom: '1px solid var(--color-border)',
		verticalAlign: 'top',
	},
	emailCell: {
		position: 'relative',
		paddingTop: '30px',
	},
	emailCellEditButton: {
		position: 'absolute',
		top: '8px',
		right: '8px',
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		borderRadius: '6px',
		padding: '4px 8px',
		fontSize: '11px',
		lineHeight: 1,
		cursor: 'pointer',
	},
	additionalEmailList: {
		margin: '8px 0 0 18px',
		padding: 0,
		fontSize: '12px',
	},
	identityNameList: {
		margin: '6px 0 0 18px',
		padding: 0,
		fontSize: '12px',
	},
	overviewTreeHeader: {
		padding: '4px 0',
		fontSize: '12px',
	},
	treeTitle: {
		fontWeight: 600,
		fontSize: '12px',
		color: 'var(--color-main-text)',
	},
	accountTreeList: {
		margin: '2px 0 0 12px',
		padding: 0,
		listStyle: 'none',
		display: 'grid',
		gap: '6px',
	},
	accountTreeRow: {
		margin: 0,
		padding: 0,
	},
	identityEntryRow: {
		display: 'grid',
		gridTemplateColumns: 'minmax(220px, 1fr) 76px 64px 64px 64px',
		alignItems: 'center',
		gap: '8px',
	},
	identityColumnsHeader: {
		display: 'grid',
		gridTemplateColumns: 'minmax(220px, 1fr) 76px 64px 64px 64px',
		alignItems: 'center',
		gap: '8px',
		fontSize: '11px',
		color: 'var(--color-text-maxcontrast)',
		fontWeight: 600,
		marginBottom: '2px',
	},
	identityHeaderCell: {
		lineHeight: 1.2,
	},
	identitySignatureHeader: {
		gridColumn: '2 / span 2',
		textAlign: 'center',
	},
	identityAccountHeader: {
		gridColumn: '4 / span 2',
		textAlign: 'center',
	},
	identitySignatureColumn: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	identitySetColumn: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	identityDeleteColumn: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	identityEditColumn: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	identityTreeItem: {
		margin: 0,
		padding: 0,
	},
	additionalAccountTreeRow: {
		marginTop: '4px',
		paddingTop: '2px',
		borderTop: '1px solid var(--color-border)',
		paddingLeft: '2px',
		borderLeft: '2px solid var(--color-border)',
	},
	additionalAccountTreeCell: {
		color: 'var(--color-text-maxcontrast)',
		fontStyle: 'italic',
	},
	overviewTreeCell: {
		display: 'flex',
		alignItems: 'baseline',
		gap: '6px',
		overflow: 'visible',
	},
	identitySignatureWrapper: {
		position: 'relative',
		cursor: 'pointer',
		border: 'none',
		background: 'transparent',
		padding: '0',
		fontSize: '12px',
		lineHeight: 1,
	},
	identitySignatureSetButton: {
		marginLeft: '6px',
		border: '1px solid var(--color-border)',
		borderRadius: '6px',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		padding: '1px 6px',
		lineHeight: 1,
		fontSize: '12px',
		cursor: 'pointer',
	},
	identitySignatureTooltip: {
		position: 'absolute',
		top: '50%',
		left: '100%',
		transform: 'translateY(-50%)',
		marginLeft: '8px',
		zIndex: 20,
		minWidth: '220px',
		maxWidth: '420px',
		background: 'var(--color-main-background)',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		boxShadow: '0 4px 16px rgba(0, 0, 0, 0.2)',
		padding: '8px',
	},
	identitySignatureTooltipPre: {
		margin: 0,
		maxHeight: '220px',
		overflow: 'auto',
		fontSize: '12px',
		lineHeight: 1.35,
		background: 'var(--color-background-hover)',
		border: '1px solid var(--color-border)',
		borderRadius: '6px',
		padding: '6px 8px',
		fontFamily: 'monospace',
		whiteSpace: 'pre-wrap',
		wordBreak: 'break-word',
	},
	modalBackdrop: {
		position: 'fixed',
		inset: 0,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		background: 'rgba(0, 0, 0, 0.4)',
		zIndex: 1000,
		padding: '16px',
	},
	modalCard: {
		width: 'min(700px, 94vw)',
		maxHeight: '90vh',
		overflow: 'auto',
		background: 'var(--color-main-background)',
		border: '1px solid var(--color-border)',
		borderRadius: '10px',
		padding: '16px',
		boxShadow: '0 10px 28px rgba(0, 0, 0, 0.25)',
	},
	modalTitle: {
		margin: '0 0 8px',
		fontSize: '16px',
		fontWeight: 600,
		color: 'var(--color-main-text)',
	},
	modalText: {
		margin: '0 0 8px',
		fontSize: '13px',
		color: 'var(--color-text-maxcontrast)',
	},
	modalTextarea: {
		width: '100%',
		minWidth: '100%',
		boxSizing: 'border-box',
		minHeight: '260px',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		padding: '10px 12px',
		fontSize: '13px',
		fontFamily: 'monospace',
		resize: 'vertical',
	},
	modalButtonRow: {
		display: 'flex',
		alignItems: 'center',
		gap: '10px',
		marginTop: '10px',
	},
	treeConnector: {
		color: 'var(--color-text-maxcontrast)',
		fontFamily: 'monospace',
		lineHeight: 1,
		width: '16px',
		flexShrink: 0,
	},
	treeContainer: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '10px',
		background: 'var(--color-main-background)',
		overflowX: 'auto',
	},
	treeLevel: {
		display: 'grid',
		gap: '8px',
	},
	treeRow: {
		display: 'grid',
		gridTemplateColumns: 'minmax(220px, 1fr) minmax(220px, 1fr)',
		gap: '8px',
	},
	treeKeyInput: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '8px 10px',
		fontSize: '13px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		width: '100%',
		boxSizing: 'border-box',
		minWidth: '220px',
	},
	treeValueInput: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '8px 10px',
		fontSize: '13px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		width: '100%',
		boxSizing: 'border-box',
		minWidth: '220px',
	},
	subheading: {
		margin: '18px 0 8px',
		fontSize: '16px',
		fontWeight: 600,
	},
	userSummaryText: {
		display: 'inline-block',
		margin: '0',
		padding: '8px 12px',
		borderRadius: '8px',
		border: '1px solid var(--color-border)',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		fontSize: '13px',
		minWidth: 'min(100%, 320px)',
		maxWidth: '560px',
		boxSizing: 'border-box',
	},
	inactiveWarning: {
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		width: '16px',
		height: '16px',
		borderRadius: '50%',
		background: 'var(--color-error)',
		color: 'white',
		fontWeight: 700,
		fontSize: '11px',
		marginLeft: '8px',
		lineHeight: 1,
	},
	statusWithTooltip: {
		position: 'relative',
		display: 'inline-block',
	},
	tooltipPanel: {
		position: 'absolute',
		top: '24px',
		left: 0,
		zIndex: 20,
		minWidth: '340px',
		maxWidth: '520px',
		background: 'var(--color-main-background)',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		boxShadow: '0 4px 16px rgba(0, 0, 0, 0.2)',
		padding: '10px',
	},
	tooltipPre: {
		margin: 0,
		maxHeight: '240px',
		overflow: 'auto',
		fontSize: '12px',
		lineHeight: 1.35,
		background: 'var(--color-background-hover)',
		border: '1px solid var(--color-border)',
		borderRadius: '6px',
		padding: '8px',
		fontFamily: 'monospace',
		whiteSpace: 'pre-wrap',
		wordBreak: 'break-word',
	},
	inlineActionButton: {
		marginLeft: '8px',
		padding: '2px 6px',
		borderRadius: '4px',
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		cursor: 'pointer',
		fontSize: '12px',
		lineHeight: 1,
	},
	overviewList: {
		margin: '8px 0 0 18px',
		padding: 0,
		display: 'grid',
		gap: '8px',
	},
};

export { styles };
