import type { CSSProperties } from 'vue';

const proseMaxWidth = '65ch';

const styles: Record<string, CSSProperties> = {
	page: {
		background: 'var(--color-main-background)',
		height: '100%',
		minHeight: '100%',
		width: '100%',
		maxWidth: 'none',
		padding: 0,
		boxSizing: 'border-box',
		overflow: 'hidden',
		display: 'flex',
		flexDirection: 'column',
	},
	formSection: {
		width: '100%',
	},
	fullWidthSection: {
		width: '100%',
		maxWidth: 'none',
	},
	proseSectionContent: {
		width: '100%',
		maxWidth: proseMaxWidth,
	},
	proseContent: {
		width: '100%',
		maxWidth: proseMaxWidth,
	},
	form: {
		display: 'grid',
		gap: '10px',
	},
	fieldLabel: {
		fontWeight: 600,
		fontSize: '14px',
		color: 'var(--color-main-text)',
	},
	checkboxRow: {
		display: 'inline-flex',
		alignItems: 'center',
		gap: '8px',
		marginTop: '10px',
	},
	input: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '10px 12px',
		fontSize: '14px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		width: '100%',
		minWidth: 'min(100%, 320px)',
		maxWidth: '100%',
		boxSizing: 'border-box',
	},
	addUserInput: {
		maxWidth: '36ch',
	},
	validationMessage: {
		margin: 0,
		color: 'var(--color-error)',
		fontSize: '13px',
	},
	hintText: {
		margin: 0,
		color: 'var(--color-text-maxcontrast)',
		fontSize: '13px',
	},
	introText: {
		margin: '0 0 16px',
		padding: '12px 14px',
		color: 'var(--color-text-maxcontrast)',
		fontSize: '13px',
		background: 'var(--color-background-hover)',
		borderRadius: '8px',
	},
	submitButton: {
		marginTop: '6px',
		padding: '10px 12px',
		borderRadius: '8px',
		border: '1px solid var(--color-primary-element)',
		background: 'var(--color-primary-element)',
		color: 'var(--color-primary-element-text)',
		cursor: 'pointer',
		width: 'fit-content',
	},
	buttonRow: {
		display: 'flex',
		alignItems: 'center',
		gap: '10px',
	},
	mailboxRow: {
		display: 'flex',
		flexWrap: 'wrap',
		alignItems: 'start',
		gap: '10px',
		width: 'fit-content',
		maxWidth: '100%',
	},
	fieldWithNoteRow: {
		display: 'flex',
		flexWrap: 'wrap',
		alignItems: 'center',
		gap: '10px',
	},
	radioGroup: {
		display: 'grid',
		gap: '6px',
	},
	radioOption: {
		display: 'flex',
		alignItems: 'start',
		gap: '8px',
		fontSize: '14px',
		color: 'var(--color-main-text)',
		cursor: 'pointer',
	},
	collapsibleSection: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '8px 12px',
	},
	collapsibleSummary: {
		fontWeight: 600,
		fontSize: '14px',
		color: 'var(--color-main-text)',
		cursor: 'pointer',
	},
	collapsibleContent: {
		display: 'grid',
		gap: '10px',
		marginTop: '10px',
	},
	clearButton: {
		marginTop: '6px',
		padding: '10px 12px',
		borderRadius: '8px',
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		cursor: 'pointer',
		width: 'fit-content',
	},
	pronounsRow: {
		display: 'flex',
		flexWrap: 'wrap',
		gap: '8px',
		alignItems: 'center',
	},
	iconButton: {
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		borderRadius: '6px',
		padding: '2px',
		width: '24px',
		height: '24px',
		lineHeight: 1,
		cursor: 'pointer',
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	entryDeleteButton: {
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		borderRadius: '6px',
		padding: '4px 8px',
		lineHeight: 1.1,
		fontSize: '11px',
		fontWeight: 600,
		cursor: 'pointer',
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		minWidth: '32px',
		minHeight: '26px',
		whiteSpace: 'nowrap',
	},
	entryEditButton: {
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		borderRadius: '6px',
		padding: '4px 8px',
		lineHeight: 1.1,
		fontSize: '11px',
		fontWeight: 600,
		cursor: 'pointer',
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		minWidth: '32px',
		minHeight: '26px',
		whiteSpace: 'nowrap',
	},
	quickFillLinks: {
		display: 'inline-flex',
		flexWrap: 'wrap',
		alignItems: 'center',
		gap: '10px',
	},
	quickFillLink: {
		border: 'none',
		background: 'transparent',
		color: 'var(--color-primary-element)',
		cursor: 'pointer',
		padding: 0,
		fontSize: '13px',
		lineHeight: 1.2,
		textDecoration: 'underline',
		textUnderlineOffset: '2px',
		whiteSpace: 'nowrap',
	},
	inlineLink: {
		color: 'var(--color-primary-element)',
		textDecoration: 'underline',
		textUnderlineOffset: '2px',
	},
	successMessage: {
		margin: 0,
		color: 'var(--color-success)',
		fontSize: '13px',
	},
	outputBox: {
		marginTop: '8px',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '10px 12px',
		fontSize: '13px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		minHeight: '96px',
		minWidth: 'min(100%, 320px)',
		width: '100%',
		maxWidth: '72ch',
		boxSizing: 'border-box',
		resize: 'vertical',
	},
	templateBox: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '10px 12px',
		fontSize: '13px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		minHeight: '420px',
		minWidth: 'min(100%, 320px)',
		width: '100%',
		maxWidth: '80ch',
		boxSizing: 'border-box',
		resize: 'vertical',
	},
	tableWrapper: {
		display: 'inline-block',
		width: 'fit-content',
		maxWidth: '100%',
		overflowX: 'auto',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
	},
	table: {
		width: 'auto',
		maxWidth: '100%',
		borderCollapse: 'collapse',
	},
	tableHeader: {
		textAlign: 'left',
		padding: '10px 12px',
		fontSize: '13px',
		borderBottom: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
	},
	tableCell: {
		padding: '10px 12px',
		fontSize: '13px',
		borderBottom: '1px solid var(--color-border)',
		verticalAlign: 'middle',
		minWidth: 0,
	},
	emailCell: {
		minWidth: 0,
	},
	emailCellLayout: {
		display: 'flex',
		alignItems: 'center',
		gap: '10px',
		minWidth: 0,
	},
	emailCellContent: {
		flex: '1 1 auto',
		minWidth: 0,
	},
	emailCellEditButton: {
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		borderRadius: '6px',
		padding: '2px',
		width: '24px',
		height: '24px',
		lineHeight: 1,
		cursor: 'pointer',
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	squareIcon: {
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		width: '16px',
		height: '16px',
		lineHeight: 1,
	},
	additionalEmailList: {
		margin: '8px 0 0 18px',
		padding: 0,
		fontSize: '12px',
	},
	identityNameList: {
		margin: '6px 0 0 18px',
		padding: 0,
		fontSize: '12px',
	},
	overviewTreeHeader: {
		padding: '4px 0',
		fontSize: '12px',
	},
	treeTitle: {
		fontWeight: 600,
		fontSize: '12px',
		color: 'var(--color-main-text)',
	},
	accountTreeList: {
		margin: '2px 0 0 12px',
		padding: 0,
		listStyle: 'none',
		display: 'inline-grid',
		gap: '6px',
		width: 'auto',
		justifyItems: 'start',
	},
	accountTreeListEditable: {
		margin: '2px 0 0 12px',
		padding: 0,
		listStyle: 'none',
		display: 'grid',
		gap: '6px',
		width: 'max-content',
		justifyItems: 'stretch',
	},
	accountTreeRow: {
		margin: 0,
		padding: 0,
	},
	identityEntryRow: {
		display: 'grid',
		gridTemplateColumns: 'minmax(0, 1fr) 120px',
		alignItems: 'center',
		columnGap: '22px',
		rowGap: '8px',
		minWidth: 0,
		width: '100%',
	},
	identityEntryRowReadOnly: {
		display: 'grid',
		gridTemplateColumns: 'minmax(0, 1fr)',
		alignItems: 'center',
		minWidth: 0,
		width: '100%',
	},
	identityCompactEntryRow: {
		gridTemplateColumns: '16px minmax(0, 1fr) 120px',
		columnGap: '6px',
		rowGap: '6px',
		paddingBlock: '1px',
	},
	identityColumnsHeader: {
		display: 'grid',
		gridTemplateColumns: 'minmax(0, 1fr) 120px',
		alignItems: 'center',
		columnGap: '22px',
		fontSize: '11px',
		color: 'var(--color-text-maxcontrast)',
		fontWeight: 600,
		marginBottom: '2px',
		minWidth: 0,
	},
	identityHeaderCell: {
		lineHeight: 1.2,
	},
	identitySignatureHeader: {
		textAlign: 'center',
	},
	identityAccountHeader: {
		textAlign: 'left',
	},
	identityActionsColumn: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'flex-end',
		width: '120px',
	},
	identityActionButtonGroup: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'flex-end',
		gap: '6px',
	},
	identityTreeItem: {
		margin: '0 0 0 34px',
		padding: 0,
		listStyle: 'none',
	},
	identityListMarker: {
		color: 'var(--color-text-maxcontrast)',
		fontWeight: 600,
		textAlign: 'center',
		lineHeight: 1,
	},
	additionalAccountTreeRow: {
		marginTop: '4px',
		paddingTop: '2px',
		paddingLeft: '2px',
	},
	additionalAccountTreeCell: {
		color: 'var(--color-text-maxcontrast)',
		fontStyle: 'italic',
	},
	overviewTreeCell: {
		display: 'flex',
		alignItems: 'baseline',
		gap: '6px',
		overflow: 'hidden',
		minWidth: 0,
		flexWrap: 'wrap',
		wordBreak: 'break-word',
	},
	identityTreeCell: {
		paddingLeft: 0,
	},
	identitySignatureWrapper: {
		position: 'relative',
		cursor: 'pointer',
		border: 'none',
		background: 'transparent',
		padding: '0',
		fontSize: '12px',
		lineHeight: 1,
	},
	identitySignatureButton: {
		border: '1px solid var(--color-border)',
		borderRadius: '6px',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		padding: '4px 8px',
		lineHeight: 1.1,
		fontSize: '11px',
		fontWeight: 600,
		cursor: 'pointer',
		whiteSpace: 'nowrap',
		display: 'inline-flex',
		alignItems: 'center',
		gap: '6px',
		minWidth: '32px',
		minHeight: '26px',
	},
	disabledActionButton: {
		opacity: 0.45,
		cursor: 'not-allowed',
		filter: 'saturate(0.7)',
	},
	identitySignatureTooltip: {
		position: 'absolute',
		top: '50%',
		left: '100%',
		transform: 'translateY(-50%)',
		marginLeft: '8px',
		zIndex: 20,
		minWidth: '220px',
		maxWidth: '420px',
		background: 'var(--color-main-background)',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		boxShadow: '0 4px 16px rgba(0, 0, 0, 0.2)',
		padding: '8px',
	},
	identitySignatureTooltipPre: {
		margin: 0,
		maxHeight: '220px',
		overflow: 'auto',
		fontSize: '12px',
		lineHeight: 1.35,
		background: 'var(--color-background-hover)',
		border: '1px solid var(--color-border)',
		borderRadius: '6px',
		padding: '6px 8px',
		fontFamily: 'monospace',
		whiteSpace: 'pre-wrap',
		wordBreak: 'break-word',
	},
	modalBackdrop: {
		position: 'fixed',
		inset: 0,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		background: 'rgba(0, 0, 0, 0.4)',
		zIndex: 2000,
		padding: '16px',
	},
	modalCard: {
		width: 'min(700px, 94vw)',
		maxHeight: '90vh',
		overflow: 'auto',
		background: 'var(--color-main-background)',
		border: '1px solid var(--color-border)',
		borderRadius: '10px',
		padding: '16px',
		boxShadow: '0 10px 28px rgba(0, 0, 0, 0.25)',
	},
	signatureModalCard: {
		width: 'min(1000px, 96vw)',
		maxHeight: '90vh',
		overflow: 'auto',
		background: 'var(--color-main-background)',
		border: '1px solid var(--color-border)',
		borderRadius: '10px',
		padding: '16px',
		boxShadow: '0 10px 28px rgba(0, 0, 0, 0.25)',
	},
	modalTitle: {
		margin: '0 0 8px',
		fontSize: '16px',
		fontWeight: 600,
		color: 'var(--color-main-text)',
	},
	modalText: {
		margin: '0 0 8px',
		fontSize: '13px',
		color: 'var(--color-text-maxcontrast)',
	},
	modalTextarea: {
		width: '100%',
		minWidth: '100%',
		boxSizing: 'border-box',
		minHeight: '260px',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		padding: '10px 12px',
		fontSize: '13px',
		fontFamily: 'monospace',
		maxWidth: proseMaxWidth,
		resize: 'vertical',
	},
	signatureEditorLayout: {
		display: 'flex',
		flexWrap: 'wrap',
		gap: '16px',
		alignItems: 'start',
	},
	signatureEditorPane: {
		display: 'grid',
		gap: '10px',
		flex: '0 1 80ch',
		maxWidth: '80ch',
	},
	signaturePreviewPane: {
		display: 'grid',
		gap: '0',
		minWidth: 0,
		flex: '0 1 80ch',
		maxWidth: '80ch',
	},
	signaturePreviewHtml: {
		minHeight: '260px',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		background: 'var(--color-main-background)',
		padding: '10px 12px',
		overflow: 'auto',
	},
	signaturePreviewPre: {
		margin: 0,
		minHeight: '260px',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		background: 'var(--color-main-background)',
		padding: '10px 12px',
		overflow: 'auto',
		fontSize: '13px',
		lineHeight: 1.35,
		fontFamily: 'monospace',
		whiteSpace: 'pre-wrap',
		wordBreak: 'break-word',
	},
	modalButtonRow: {
		display: 'flex',
		alignItems: 'center',
		gap: '10px',
		marginTop: '10px',
	},
	treeConnector: {
		display: 'inline-block',
		width: '14px',
		height: '10px',
		flexShrink: 0,
		borderLeft: '1.5px solid var(--color-text-maxcontrast)',
		borderBottom: '1.5px solid var(--color-text-maxcontrast)',
		boxSizing: 'border-box',
		transform: 'translateY(-1px)',
		opacity: 0.9,
	},
	treeContainer: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '10px',
		background: 'var(--color-main-background)',
		overflowX: 'auto',
	},
	treeLevel: {
		display: 'grid',
		gap: '8px',
	},
	treeRow: {
		display: 'grid',
		gridTemplateColumns: 'minmax(220px, 1fr) minmax(220px, 1fr)',
		gap: '8px',
	},
	treeKeyInput: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '8px 10px',
		fontSize: '13px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		width: '100%',
		boxSizing: 'border-box',
		minWidth: '180px',
		maxWidth: '18rem',
	},
	treeValueInput: {
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		padding: '8px 10px',
		fontSize: '13px',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		width: '100%',
		boxSizing: 'border-box',
		minWidth: '220px',
		maxWidth: '42rem',
	},
	mailboxNamesGrid: {
		display: 'inline-grid',
		gridTemplateColumns: 'fit-content(18rem) fit-content(42rem) fit-content(42rem)',
		gap: '8px',
		alignItems: 'start',
		maxWidth: '100%',
	},
	mailboxNamesHeader: {
		fontSize: '12px',
		fontWeight: 600,
		color: 'var(--color-text-maxcontrast)',
		textTransform: 'uppercase',
		letterSpacing: '0.04em',
		padding: '0 2px 4px',
	},
	mailboxNamesRow: {
		display: 'contents',
	},
	mailboxPrefixField: {
		display: 'grid',
		gridTemplateColumns: 'minmax(0, 1fr) auto',
		gap: '8px',
		alignItems: 'center',
	},
	mailboxLocaleField: {
		display: 'grid',
		gap: '4px',
	},
	mailboxLocaleLabel: {
		fontSize: '12px',
		fontWeight: 600,
		color: 'var(--color-text-maxcontrast)',
		textTransform: 'uppercase',
		letterSpacing: '0.04em',
		paddingLeft: '2px',
	},
	mailboxDeleteButton: {
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		borderRadius: '6px',
		width: '28px',
		height: '28px',
		lineHeight: 1,
		cursor: 'pointer',
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		padding: 0,
		flexShrink: 0,
	},
	mailboxAddButton: {
		padding: '10px 12px',
		borderRadius: '8px',
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		cursor: 'pointer',
		width: 'fit-content',
		minWidth: '44px',
		fontSize: '18px',
		lineHeight: 1,
	},
	mailboxNamesAddRow: {
		display: 'flex',
		justifyContent: 'flex-start',
		marginTop: '10px',
	},
	subheading: {
		margin: '18px 0 8px',
		fontSize: '16px',
		fontWeight: 600,
	},
	userSummaryText: {
		display: 'inline-block',
		margin: '0',
		padding: '8px 12px',
		borderRadius: '8px',
		border: '1px solid var(--color-border)',
		background: 'var(--color-main-background)',
		color: 'var(--color-main-text)',
		fontSize: '13px',
		minWidth: 'min(100%, 320px)',
		maxWidth: '560px',
		boxSizing: 'border-box',
	},
	inactiveWarning: {
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
		width: '16px',
		height: '16px',
		borderRadius: '50%',
		background: 'var(--color-error)',
		color: 'white',
		fontWeight: 700,
		fontSize: '11px',
		marginLeft: '8px',
		lineHeight: 1,
	},
	statusWithTooltip: {
		position: 'relative',
		display: 'inline-block',
	},
	tooltipPanel: {
		position: 'absolute',
		top: '24px',
		left: 0,
		zIndex: 20,
		minWidth: '340px',
		maxWidth: '520px',
		background: 'var(--color-main-background)',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		boxShadow: '0 4px 16px rgba(0, 0, 0, 0.2)',
		padding: '10px',
	},
	popoverBackdrop: {
		position: 'fixed',
		inset: 0,
		zIndex: 1900,
		background: 'transparent',
	},
	popoverPanel: {
		position: 'fixed',
		zIndex: 1901,
		background: 'var(--color-main-background)',
		border: '1px solid var(--color-border)',
		borderRadius: '8px',
		boxShadow: '0 10px 28px rgba(0, 0, 0, 0.25)',
		padding: '10px',
		display: 'flex',
		flexDirection: 'column',
		overflow: 'hidden',
	},
	diffScroller: {
		flex: '1 1 auto',
		minHeight: 0,
		overflow: 'auto',
		border: '1px solid var(--color-border)',
		borderRadius: '6px',
	},
	diffTable: {
		width: '100%',
		borderCollapse: 'collapse',
		fontSize: '12px',
		fontFamily: 'monospace',
	},
	diffTableHeader: {
		position: 'sticky',
		top: 0,
		background: 'var(--color-background-hover)',
		borderBottom: '1px solid var(--color-border)',
		padding: '6px 8px',
		textAlign: 'left',
		fontSize: '12px',
		fontWeight: 600,
		whiteSpace: 'nowrap',
	},
	diffTableCell: {
		padding: '4px 8px',
		borderBottom: '1px solid var(--color-border)',
		verticalAlign: 'top',
		whiteSpace: 'pre-wrap',
		wordBreak: 'break-word',
	},
	diffRowChanged: {
		background: 'rgba(255, 193, 7, 0.18)',
	},
	diffColumns: {
		display: 'grid',
		gridTemplateColumns: '1fr 1fr',
		gap: '10px',
		overflow: 'auto',
	},
	tooltipHeader: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: '8px',
		marginBottom: '6px',
		fontSize: '13px',
		color: 'var(--color-main-text)',
	},
	tooltipPre: {
		margin: 0,
		maxHeight: '240px',
		overflow: 'auto',
		fontSize: '12px',
		lineHeight: 1.35,
		background: 'var(--color-background-hover)',
		border: '1px solid var(--color-border)',
		borderRadius: '6px',
		padding: '8px',
		fontFamily: 'monospace',
		whiteSpace: 'pre-wrap',
		wordBreak: 'break-word',
	},
	inlineActionButton: {
		marginLeft: '8px',
		padding: '2px',
		borderRadius: '6px',
		border: '1px solid var(--color-border)',
		background: 'var(--color-background-hover)',
		color: 'var(--color-main-text)',
		cursor: 'pointer',
		lineHeight: 1,
		width: '24px',
		height: '24px',
		display: 'inline-flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	overviewList: {
		margin: '8px 0 0 18px',
		padding: 0,
		display: 'grid',
		gap: '8px',
	},
	monospaceCode: {
		fontFamily: '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
		fontSize: '0.95em',
		fontVariantLigatures: 'none',
		overflowWrap: 'anywhere',
		wordBreak: 'break-word',
	},
};

export { styles };
